services:
  # Service for spring boot backend
  app:
    image: app
    container_name: app
    build:
      context: .
    ports:
      - "3000:8080"
    depends_on:
      neo4j-db:
        condition: service_healthy # Wait for neo4j to be ready
    links:
      - neo4j-db
    environment:
      NEO4J_URI: bolt://neo4j-db:7687
      NEO4J_PASSWORD: mkprops123

  # Service for Neo4j database
  neo4j-db:
    image: neo4j:latest
    container_name: app-neo4j-db
    restart: on-failure
    environment:
      NEO4J_AUTH: neo4j/mkprops123
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j-db:/data
    healthcheck:
      test: cypher-shell --username neo4j --password mkprops123 'MATCH (n) RETURN COUNT(n);' # Checks if neo4j server is up and running
      interval: 10s
      timeout: 10s
      retries: 5

volumes:
  neo4j-db:
