services:
  # Service for spring boot backend
  app:
    image: app
    container_name: app
    build:
      context: .
    ports:
      - "3000:8080"
    links:
      - postgres
    environment:
      POSTGRES_URI: postgresql://postgres:${POSTGRES_PASSWORD}@postgres:7687/finance-g2

  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - postgredb:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=postgres
      - POSTGRES_DB=finance-g2

volumes:
  postgredb:
