services:
  # Service for spring boot backend
  app:
    image: app
    container_name: app
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      neo4j-db:
        condition: service_healthy # Wait for neo4j to be ready
    links:
      - neo4j-db
    environment:
      NEO4J_URI: bolt://neo4j-db:7687
      NEO4J_PASSWORD: secret

  # Service for Neo4j database
  neo4j-db:
    image: neo4j:4.1.4
    container_name: app-neo4j-db
    restart: on-failure
    environment:
      NEO4J_AUTH: neo4j/secret
    volumes:
      - neo4j-db:/data

volumes:
  neo4j-db: